### ISSUE TITLE
Some Files Missing

### ISSUE THREAD

**Issue by ghost** [LVPlayground/bot-sonium#3]
Hello !i just tryed to run Sonium but i notice a file missing and a fatal error 

the missing file
/vendor/autoload.php';

Yassine

**Comment by debuggest3** [comment]
This project uses Composer for dependency management, see https://getcomposer.org/doc/01-basic-usage.md#installing-dependencies.

For the missing file you are reporting is created by Composer. Files created by dependency management frameworks and the dependencies themselves are not committed to the repository by default.

Please consult the Composer documentation for further reference.

**Comment by ghost** [comment]
Hello You can tell me how to get it ??? with shell ?
